# Generated by Django 5.1.4 on 2024-12-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.curso')),
            ],
        ),
    ]
