# Generated by Django 5.1.4 on 2024-12-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome_evento',
            new_name='nome_curso',
        ),
    ]
