# Generated by Django 5.1.4 on 2024-12-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_rename_nome_evento_curso_nome_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('desc_breve', models.CharField(max_length=255)),
                ('desc_detalhada', models.CharField(max_length=511)),
                ('data_ini', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeHora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_hora', models.CharField(max_length=255)),
                ('horas_max', models.IntegerField()),
                ('horas_max_atv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fs_path', models.CharField(max_length=511)),
                ('alunoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
                ('eventoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(blank=True, max_length=511, null=True)),
                ('alunoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
                ('eventoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('falta', models.BooleanField(default=False)),
                ('eventoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.evento')),
                ('inscricaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.curso')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='professorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.professor'),
        ),
        migrations.CreateModel(
            name='HoraComplementar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('alunoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.aluno')),
                ('certificadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.certificado')),
                ('tipoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.tipodehora')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.tipodehora'),
        ),
    ]
