# Generated by Django 5.1.4 on 2024-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_coordenador_imagem_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem_aluno',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='perfil_aluno/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='imagem_professor',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='perfil_professor/'),
        ),
    ]
